# Generated by Django 3.2.4 on 2021-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_auto_20210608_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role_tag',
            field=models.ManyToManyField(blank=True, related_name='roletag', to='profileapp.RoleTag'),
        ),
    ]
