# Generated by Django 3.2 on 2021-05-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
        ('projectapp', '0004_alter_project_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='profileapp.Profile'),
        ),
    ]
