# Generated by Django 3.2 on 2021-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_alter_project_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='index',
            field=models.CharField(default='0001', max_length=10),
            preserve_default=False,
        ),
    ]
